Online_School/urls.py
from django.contrib import admin
from django.urls import path, include
from course_app.views import HomePage
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name='home' ),
    path('', include('course_app.urls')),
]  

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

course_app/urls.py
from django.urls import path
from course_app.views import SignUpView, coursePage, LogInView, log_out, checkout, MyCourseList
app_name = 'course_app'

urlpatterns = [
    path('course/<str:slug>', coursePage, name = 'coursepage'),
    path('signup', SignUpView.as_view(), name='signup'),
    path('login', LogInView.as_view(), name='login'),
    path('logout', log_out, name='logout'),
    path('check-out/<str:slug>', checkout, name = 'checkout'),
    path('mycourses/', MyCourseList.as_view(), name='mycourses'),
]

course_app/models.py
from django.db import models

# Create your models here.

course_app/models/courses.py
from django.db import models


class Course(models.Model):
    name = models.CharField(max_length=50, null= False)
    slug = models.CharField(max_length=265, null=False, unique=True)
    description = models.CharField(max_length=255, null=True)
    price = models.IntegerField(null=False) 
    discount = models.IntegerField(null=False, default=0)
    active = models.BooleanField(default=False)
    thumbnail = models.ImageField(upload_to='files/thumbnail')
    date = models.DateTimeField(auto_now_add=True)
    resource = models.FileField(upload_to='files/resource')
    length = models.IntegerField(null=False)
    
    def __str__(self):
        return self.name

# this model should not display so use abstract
class CourseProperty(models.Model):
    description = models.CharField(max_length=200, null=False)
    course = models.ForeignKey(Course, null=False, on_delete=models.CASCADE)
    
    class Meta:
        abstract = True


class Tag(CourseProperty):
    pass
    
    
class Prerequisite(CourseProperty):
    pass
    
class Learning(CourseProperty):
    pass

class CouponCode(models.Model):
    code = models.CharField(max_length=50)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='coupons')
    discount = models.IntegerField(default=0)

course_app/models/payment.py
from django.db import models
from course_app.models import Course, UserCourse
from django.contrib.auth.models import User

class Payment(models.Model):
    order_id = models.CharField(max_length=100, null = False)
    payment_id = models.CharField(max_length=100)
    user_course = models.ForeignKey(UserCourse, null= True, blank=True, on_delete=models.CASCADE) 
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)
    

course_app/models/user_course.py
from django.db import models
from course_app.models.courses import Course
from django.contrib.auth.models import User

class UserCourse(models.Model):
    user = models.ForeignKey(User, null= False, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, null= False, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    
    
    def __str__(self):
        return f'{self.user.username} enrolled {self.course.name}'

course_app/models/video.py
from django.db import models
from course_app.models.courses import Course


class Video(models.Model):
    title = models.CharField(max_length=100, null=False)
    course = models.ForeignKey(Course, null= False, on_delete=models.CASCADE)
    serial_number = models.IntegerField(null=False)
    video_id = models.CharField(max_length=30, null= False)
    is_preview = models.BooleanField(default=False)
    
    def __str__(self):
        return self.title
    
    

course_app/forms/login_form.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import ValidationError
from django.contrib.auth import authenticate, login


class LoginForm(AuthenticationForm):
    
    username = forms.EmailField(max_length=25 , required = True , label='Email Address')

    def clean(self):
        email = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = None
        try:
            user = User.objects.get(email = email)
            result = authenticate(username = user.username , password = password)

            if(result is not None):
                return result
            else:
                raise ValidationError("Email or Password invalid")
        except:
            raise ValidationError("Email or Password invalid")

course_app/forms/registration_form.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import ValidationError

class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=20, required=True)
    last_name = forms.CharField(max_length=20, required=True)
    email = forms.EmailField(max_length=80, required=True)
    class Meta:
        model = User
        fields = ['first_name','last_name','username','email', 'password1', 'password2']
        
        
    def clean_email(self):
        email = self.cleaned_data['email']
        user = None
        try:
            user = User.objects.get(email=email)
        except:
            return email
        
        if (user is not None):
            raise ValidationError('User already exists')

course_app/views/checkout.py
from django.shortcuts import render, HttpResponse, redirect
from course_app.models import Course, Video, UserCourse, CouponCode
from course_app.models import Payment
from sslcommerz_lib import SSLCOMMERZ 
from django.contrib.auth.decorators import login_required


# API Integrations
KEY_ID = 'thevi6552744e8167c'
KEY_SECRET = 'thevi6552744e8167c@ssl'

settings = { 'store_id': KEY_ID, 'store_pass': KEY_SECRET, 'issandbox': True }
sslcommez = SSLCOMMERZ(settings)


@login_required(login_url='/login')
def checkout(request,slug):
    course = Course.objects.get(slug = slug)
    user = request.user
    action = request.GET.get('action')
    couponcode = request.GET.get('couponcode')
    coupon_code_message = None;
    coupon = None
    payment = None
    error = None
    order = None
    amount = None
    
    if error is None:
        amount = int((course.price-(course.price * course.discount* 0.01)) * 100)
        
        if amount == 0:
            userCourse = UserCourse(user = user, course = course)
            userCourse.save()
            return redirect('/mycourses')
        
        
    if action == 'create_payment':
        print('Create order object')
        order = 'Order created'
        
        # Payment Integrations
        post_body = {}
        post_body['total_amount'] = (course.price -(course.price * course.discount * 0.01))
        post_body['currency'] = "BDT"
        post_body['tran_id'] = 'dkjfkjkfj'
        post_body['success_url'] = "your success url"
        post_body['fail_url'] = "your fail url"
        post_body['cancel_url'] = "your cancel url"
        post_body['emi_option'] = 0
        post_body['cus_name'] = "test"
        post_body['cus_email'] = "test@test.com"
        post_body['cus_phone'] = "01700000000"
        post_body['cus_add1'] = "customer address"
        post_body['cus_city'] = "Dhaka"
        post_body['cus_country'] = "Bangladesh"
        post_body['shipping_method'] = "NO"
        post_body['multi_card_name'] = ""
        post_body['num_of_item'] = 1
        post_body['product_name'] = "Test"
        post_body['product_category'] = "Test Category"
        post_body['product_profile'] = "general"
        
        response = sslcommez.hash_validate_ipn(post_body)
        print(response)

    
    if couponcode:
        try:
            coupon = CouponCode.objects.get(course =  course, code = couponcode)
        except:
            coupon_code_message = 'Invalid coupon code'
    
    diction = {'course':course, 'order':order, 'coupon':coupon, 'coupon_code_message':coupon_code_message}
    return render(request, template_name= 'course_app/checkout.html', context= diction)

course_app/views/courses.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, HttpResponse, redirect
from course_app.models import Course, Video, UserCourse
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from django.utils.decorators import method_decorator


@method_decorator(login_required(login_url= 'login'), name='dispatch')
class MyCourseList(ListView):
    template_name='course_app/mycourses.html'
    context_object_name = 'user_courses'
    
    def get_queryset(self):
        return UserCourse.objects.filter(user= self.request.user)


def coursePage(request,slug):
    course = Course.objects.get(slug=slug)
    serial_number = request.GET.get('lecture')
    videos = course.video_set.all().order_by("serial_number")
    next_lecture = 2
    preview_lecture = None
    
    if serial_number is None:
        serial_number = 1
    else:
        next_lecture = int(serial_number) + 1
        if len(videos) < next_lecture:
            next_lecture = None
        
        preview_lecture = int(serial_number) - 1
        
    
    video = Video.objects.get(serial_number=serial_number, course=course)

    if (video.is_preview is False):
        if (request.user.is_authenticated is False):
            return redirect ('course_app:login')
        else:
            user = request.user
            try:
                user_course = UserCourse.objects.get(user = user , course = course)
                error = 'You are already enrolled in this course'   
            except:
                return redirect ('course_app:checkout', slug = course.slug)
    
    
    diction = {'course':course,'video':video, 'videos':videos, 'next_lecture':next_lecture, 'preview_lecture':preview_lecture}
    return render(request, template_name= 'course_app/course_page.html', context= diction)



"""
@login_required(login_url= 'login')
def mycourses(request):
    user = request.user
    user_courses = UserCourse.objects.filter(user=user)
    diction = {'user_courses': user_courses}
    return render(request, template_name='course_app/mycourses.html', context=diction)
"""

course_app/views/homepage.py
from django.shortcuts import render
from course_app.models import Course
from django.views.generic import ListView


class HomePage(ListView):
    template_name= 'course_app/homepage.html'
    queryset = Course.objects.filter()
    context_object_name = 'courses'
    # active = False



"""
def home(request):
    #retrive
    courses = Course.objects.all()
    print(courses)
    diction =  {'courses': courses}
    return render(request, template_name= 'course_app/homepage.html', context= diction)
"""

course_app/templates/course_app/checkout.html
{% extends 'base.html'  %}
{% load course_custom_tags %}
{% load crispy_forms_tags %}


{% block css_block %}
<style>
    .display-5{
        font-size: 35px;
    }
</style>

{% endblock %}

{% block title_block %} Signup {% endblock %}


{% block body_block %}
<div class="container">
    {% if order is not None %}
    <h3 class="display-5 alert border text-center">Please Check and Continue Your Checkout</h3>
    <hr>
    {% endif %}
    <div class="text-center">
        <h3>You are going to enroll <a href="{% url 'course_app:coursepage' slug=course.slug %}">{{course.name}}</a> course.</h3> <hr>
    </div>
    <br>
    

    <div class="row">
        <div class="col mx-auto ">
            <div class="card mx-auto" style="width: 18rem;">
                <img src= "{{ course.thumbnail.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                <h5 class="card-title">{{course.name}}</h5>
                <p class="card-text">{{course.description}}</p>
                <p class="card-text"> Save {{course.discount}}% <br>
                    <span>
                        <del>{{course.price|bdt}}</del> &nbsp;
                        <span> {% cal_sellprice course.price course.discount as value %} {{value|bdt}} </span>
                    </span>
                </p>
                </div>
            </div>
        </div>

        <div class="col border rounded border-info">
            <div>
                <p class="display-5">{{course.name}}</p>
                <hr>
                {% if coupon %}
                <div>
                    <p class="alert alert-info">Coupon Code Applied Successfully!
                        You have got {{coupon.discount}}% discount.
                    </p>

                </div>
                <p class="display-5">Payable Ammount: <b>{% cal_sellprice course.price coupon.discount as value %} {{value|bdt}}</b></p> <br>
                {% else %}
                <p class="display-5">Payable Ammount: <b>{% cal_sellprice course.price course.discount as value %} {{value|bdt}}</b></p> <br>
                {% endif %}
                <a href="?action=create_payment" class="btn btn-info btn-lg"><b>Continue To Payment</b></a>
            </div>
            <br>
            <div class="border mb-3 rounded border-info">
                {%if coupon_code_message %}
                <div class="alert alert-info">
                    {{coupon_code_message}}
                </div>
                {% endif %}
                <p class="col-lg-5">Apply Coupon Code!</p>
                <form action="" method="GET">
                    <div class="col-lg-5" class="form-group">
                        <input type="text" class="form-control" name="couponcode">
                    </div> <br>
                    <div class="form-group col-lg-5"> 
                        <input type="submit" value="Apply" class="btn btn-info btn-sm">
                    </div>
                </form>
            </div>

        </div>
    </div>
    
    <br>

</div>



{% endblock %}

course_app/templates/course_app/course_page.html
{% extends 'base.html'  %}
{% load static %}
{% load course_custom_tags %}

{% block css_block %}
<link rel="stylesheet" href="{% static 'css/course_page.css' %}">
<link rel="stylesheet" href="{% static 'css/scrollbar.css' %}">

<style>
    .active-video{
        background-color: rgb(224, 75, 21);
        background: white;
    }
        a:hover{
    text-decoration: none;
    }
    a{
        color: rgb(237, 107, 7);
    }
    .active-video-link{
        background-color: grey;
        color: rgb(60, 243, 4);
    }
    .active-video-link:hover{
        text-decoration: none;
    }
    .no-preview{
        cursor: not-allowed;
    }
    </style>

{% endblock %}

{% block title_block %} Course Details {% endblock %}




{% block body_block %}


<div class="container-fluid">
    <div> <br>
        <div class="card p-3">
            <div class="row">
                <!-- Youtube Player -->
                <div class="col-9">
                    <div class="mx-auto">
                        <iframe id="player" class="mx-auto" width="100%" height="400" src="https://www.youtube.com/embed/{{video.video_id}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                    </div>
                        <div class="d-flex justify-content-between">
                            <div id="preview">
                                {% if preview_lecture %}
                                <a class="btn btn-info btn-sm"href="?lecture={{preview_lecture}}"> << Preview</a>
                                {% else %}
                                <a class="btn btn-info btn-sm disabled"href="javascript:void(0)"> << Preview</a>
                                {% endif %}
                            </div>
                            <div id="next">
                                {% if next_lecture %}
                                <a class="btn btn-info btn-sm"href="?lecture={{next_lecture}}">Next >></a>
                                {% else %}
                                <a class="btn btn-info btn-sm disabled"href="javascript:void(0)">Next >></a>
                                {% endif %}
                            </div>
                        </div>
                </div>
                <!-- Lecture List -->
                <div class="col-3">
                    <ul id="video_list" class="list-group overflow-y-scroll">
                        {% is_enrolled request course as enrolled %}
                        {% for vid in videos %}
                            
                            <li class="list-group-item {% if vid == video %} active-video {% endif %}">
                                <a class="
                                {% if not enrolled and not vid.is_preview %} text-muted no-preview {% endif %}
                                {% if vid == video %} active-video-link {% endif %}" href="?lecture={{vid.serial_number}}">
                                    {{vid}}
                                </a>
                            </li>

                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <!-- Course Details -->
        <div class="mt-3">
            <div>
                <div class="card" >
                    <div class="card-body">
                      <h5 class="card-title">{{course.name}}</h5>
                      <p class="card-text">{{course.description}}</p>
                    </div>
                  </div>
            </div>
        </div>
        <!-- Prequisite -->
        <div class="mt-3">
            <div>
                <div class="card" >
                    <div class="card-body">
                      <h5 class="card-title">Prerequisites for this course:</h5>
                      <p class="card-text">
                            {% for pre in course.prerequisite_set.all %}
                            <li>{{pre.description}}</li>
                            {% endfor %}
                      </p>
                    </div>
                  </div>
            </div>
        </div>
        <!-- Learning Materials -->
        <div class="mt-3">
            <div>
                <div class="card" >
                    <div class="card-body">
                      <h5 class="card-title">You will learn in this course:</h5>
                      <p class="card-text">
                            {% for learn in course.learning_set.all %}
                            <li>{{learn.description}}</li>
                            {% endfor %}
                      </p>
                    </div>
                  </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}



{% block js %}
<script src="{% static 'course/js/course_page.js' %}"></script>
{% endblock %}

course_app/templates/course_app/homepage.html
{% extends 'base.html'  %}
{% load course_custom_tags %}

{% block title_block %} Home Page {% endblock %}


{% block body_block %}
<!-- user-identity -->
{{request.user}}
<!-- user-identity -->

<div class="container-fluid">
    <br>
    <div class="row">
        {% for course in courses %}
        <div class="col mx-auto">
            <div class="card mx-auto" style="width: 18rem;">
                <img src= "{{ course.thumbnail.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                <h5 class="card-title">{{course.name}}</h5>
                <p class="card-text">{{course.description}}</p>
                <p class="card-text"> Save {{course.discount}}% <br>
                    <span>
                        <del>{{course.price|bdt}}</del> &nbsp;
                        <span> {% cal_sellprice course.price course.discount as value %} {{value|bdt}} </span>
                    </span>
                </p>
                
                </div>
                
                <div class="card-footer p-0">
                    <div class="row no-gutters">
                        {% if is_enrolled %}
                        <div class="col border-right">
                            <a href="#" class="btn btn-light btn-block">Start</a>
                        </div>

                        {% else %}

                        <div class="col border-right">
                            <a href="/check-out/{{course.slug}}" class="btn btn-light btn-block">Enroll Now</a>
                        </div>
                        <div class="col">
                            <a href="{% url 'course_app:coursepage' slug=course.slug %}" class="btn btn-light btn-block">Show More</a>
                        </div>

                        {% endif %}
                        
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>



{% endblock %}

course_app/templates/course_app/login.html
{% extends 'base.html'  %}
{% load crispy_forms_tags %}


{% block css_block %} {% endblock %}

{% block title_block %} Signup {% endblock %}


{% block body_block %}

<div class="container">
   <h1 class="display-2">Login Please</h1>
   <div>
      <form action="" method="POST">
         {% csrf_token %}
         {{form|crispy}}
         <input type="submit" value="Login" class="btn btn-info btn-sm">
      </form>
   </div>
</div>



{% endblock %}

course_app/templates/course_app/mycourses.html
{% extends 'base.html'  %}
{% load course_custom_tags %}
{% load crispy_forms_tags %}


{% block css_block %}
<style>
    .display-6{
        font-size: 35px;
        font-weight: 300;
    }
</style>

{% endblock %}

{% block title_block %} Signup {% endblock %}


{% block body_block %}

<div class="container">
   <h1 class="display-6">My Course List</h1> <hr> <br>

   <div class="row">
    {% for uc in user_courses %}
    <div class="col mx-auto">
        <div class="card mx-auto" style="width: 18rem;">
            <img src= "{{ uc.course.thumbnail.url }}" class="card-img-top" alt="...">
            <div class="card-body">
            <h5 class="card-title">{{uc.course.name}}</h5>
            </div>
            
            <div class="card-footer p-0">
                <div class="row no-gutters">
                    <div class="col border-right">
                        <a href="#" class="btn btn-light btn-block">Start</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>



</div>



{% endblock %}

course_app/templates/course_app/signup.html
{% extends 'base.html'  %}
{% load course_custom_tags %}
{% load crispy_forms_tags %}


{% block css_block %} {% endblock %}

{% block title_block %} Signup {% endblock %}


{% block body_block %}

<div class="container">
   <h1 class="display-5">Signup Please to Continue</h1> <br>
   <div class="center">
      <form action="/signup" method="POST">
         {% csrf_token %}
         {{form|crispy}}
         <input type="submit" value="Register" class="btn btn-secondary btn-sm">
      </form>
   </div>
</div>



{% endblock %}